name: DebugBuild
on:
  push:
    branches:
      - master
env: 
  SOLUTION_FILE_PATH: Create_Engine.sln

  CONFIGURATION: Debug
jobs: 
  build:
    runs-on: windows-2022

    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MsBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecreate: x64

      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
